### ISSUE TITLE
Remove number and string literal suffixes

### ISSUE THREAD

**Issue by Araq** [nim-lang/nif#34]
These are a weird unnecessary special case for a Lisp that cause unnecessary complexity. Instead number should be like this:

- With a `u` suffix it is an unsigned number.
- Else if the number has a dot or an `E` it is a floating point number.
- Else it is an integer.

Typed integer literals then can be modelled simply as `(suf 234 "u32")`. This takes up more space but this should be irrelevant.

**Comment by ringabout** [comment]
I'm working on `nif`
```
(.nif24)
(.vendor "Nifler")
(.dialect "nim-parsed")
@0,1,/home/wind/defs/Nim/bug.nim(stmts
 (cmd
 echo @5(tupleConstr
 @1 (suf 12 "u32")@9 12.3 @15 1200.0 @21 (suf
 7.5 "f32"
)@29"123" @36(suf "debility" "R")
)
)
)
```
